version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: ecommerce_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: strongpassword123
      POSTGRES_DB: ecommerce_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - ecommerce_network

volumes:
  pgdata:

networks:
  ecommerce_network:
